### PR TITLE
Index Page Updates

### PR DESCRIPTION
**Pull request by chrisdaaz**
updated links to hotel, dinner signups, contact info, and acknowledged partnership with university of michigan libraries.

### CODE REVIEW

**Comment by chrisdaaz** [comment]
@adamjarling ^^

am i doing this right?

**Review by adamjarling — APPROVED** [review]
@davidschober Looks like we have an up and coming Front End dev on our hands!

**Comment by adamjarling** [comment]
@cpd3149 You got it.  General pattern is when one person approves a Pull Request, then feel free to merge and you'll have an updated branch.  Nice work.

**Comment by adamjarling** [comment]
@cpd3149 Another best practice is before you make updates to a branch, do a `git fetch`, then `git pull` to make sure you're working on the latest version of the files.  If you're collaborating with other people on the repo files that is.

So since you made some updates, the next time I work on this site (which might be never since you're rocking the front end dev side), I'd go to my local directory on my machine where I have the `samvera-connect2017` repository files saved, and then in my Terminal window I'd execute the `git fetch...` commands.   

A handy tool if you're getting started with Git, to visualize the process is this:  https://www.sourcetreeapp.com/  It's invaluable for dummy-checking, and making sense of complicated branching.  Install it and if you have any questions I can walk you through it.

**Comment by davidschober** [comment]
nice work @cpd3149

**Pull request merged**
